/** Declaration file generated by dts-gen */

export function decode(dataURI: any): any;

export function encode(data: any, mediaType: any): any;

export function encodeFromFile(filePath: any): any;

export function encodeFromURL(imageURL: any, options?: any): any;

export function outputFile(dataURI: any, filePath: any): any;

